<div class="headline">
	<h2>Welcome</h2>
	<p>JMT WebDesign+Development is the portfolio of Jessica M. Tsuji. I&rsquo;m an interactive designer &amp; developer based out of Portland, OR. My passion is infusing form &amp; function into online experiences. </p>
</div>

<ul id="featuredWork">
	<li id="blend" class="featBlend project">
		<h3 class="tab">Blend Messenger</h3>
		<address>Demo: <a href="http://www.adelineinteractive.com/Blend">Launch Blend</a></address>
		<p><strong>Overview:</strong>Blend Messenger is an Ajax/PHP-based online-based instant messenger project motivated by the highly collaborative nature of our three-person development team.</p>
		<div class="gallery">
			<div class="overlay">
				<a class="previous" href="#">&laquo; Previous</a>
				<a class="view" href="/work/index/project/blend/#blend">View this Project</a>
				<a class="next" href="#">Next &raquo;</a>
			</div>
			<ul>
				<li>
					<img src="/images/work/blend_full.jpg" alt="Blend Messenger" />
				</li>
				<li>
					<img src="/images/work/blend_full2.jpg" alt="Blend Messenger" />
				</li>
			</ul>
		</div>
	</li>
	<li id="encompass" class="featEncompass project">
		<h3 class="tab">Encompass Institute</h3>
		<address>Demo: <a href="http://www.encompassinstitute.org">Launch Encompass</a></address>
		<p><strong>Overview:</strong>The EnCompass Institute is a non-profit organization based in Portland, Oregon promoting the child development theory of Natural Learning Rhythms.</p>
		<div class="gallery">
			<div class="overlay">
				<a class="previous" href="#">&laquo; Previous</a>
				<a class="view" href="/work/index/project/encompass/#encompass">View this Project</a>
				<a class="next" href="#">Next &raquo;</a>
			</div>
			<ul>
				<li>
					<img src="/images/work/encompass_full.jpg" alt="Blend Messenger" />
				</li>
				<li>
					<img src="/images/work/encompass_full2.jpg" alt="Blend Messenger" />
				</li>
				<li>
					<img src="/images/work/encompass_full3.jpg" alt="Blend Messenger" />
				</li>
				<li>
					<img src="/images/work/encompass_full4.jpg" alt="Blend Messenger" />
				</li>
			</ul>
		</div>
	</li>
	<li id="johnny" class="featJohnny project">
		<h3 class="tab">Johnny Le Films</h3>
		<address>Demo: <a href="http://www.johnnylefilms.com">Launch Johnny Le</a></address>
		<p><strong>Overview:</strong>Johnny Le is an aspiring Portland filmmaker, producer, and director. He needed a way to showcase his creative digital pieces in a medium that was equally as engaging.</p>
		<div class="gallery">
			<div class="overlay">
				<a class="previous" href="#">&laquo; Previous</a>
				<a class="view" href="/work/index/project/johnny/#johnny">View this Project</a>
				<a class="next" href="#">Next &raquo;</a>
			</div>
			<ul>
				<li>
					<img src="/images/work/johnny_full.jpg" alt="Blend Messenger" />
				</li>
				<li>
					<img src="/images/work/johnny_full2.jpg" alt="Blend Messenger" />
				</li>
				<li>
					<img src="/images/work/johnny_full3.jpg" alt="Blend Messenger" />
				</li>
			</ul>
		</div>
	</li>
	<li id="hawaiian" class="featHawaiian project">
		<h3 class="tab">Hawaiian Numbers</h3>
		<address>Demo: <a href="http://adelineinteractive.com/Jessica/hawaiianNumbers/">Launch Hawaiian Numbers</a></address>
		<p><strong>Overview:</strong>Hawaiian Numbers is a e-Learning project targeted at students of the Hawaii Public School System where the Hawaiian language is taught to grades K-9.</p>
		<div class="gallery">
			<div class="overlay">
				<a class="previous" href="#">&laquo; Previous</a>
				<a class="view" href="/work/index/project/hawaiian/#hawaiian">View this Project</a>
				<a class="next" href="#">Next &raquo;</a>
			</div>
			<ul>
				<li>
					<img src="/images/work/hawaiian_full.jpg" alt="Blend Messenger" />
				</li>
				<li>
					<img src="/images/work/hawaiian_full2.jpg" alt="Blend Messenger" />
				</li>
				<li>
					<img src="/images/work/hawaiian_full3.jpg" alt="Blend Messenger" />
				</li>
			</ul>
		</div>
	</li>
	<li class="active">
		<h3 class="arrow"></h3>
	</li>
</ul>