<div class="headline">
	<h2 class="welcome">Hello, World!</h2>
	<p class="welcome">JMT WebDesign+Development is the portfolio of Jessica M. Tsuji. I&rsquo;m an interactive designer & developer based out of Portland, OR. My passion is infusing form & function into online experiences. </p>
</div>

<ul id="featuredWork">
	<li class="featBlend project">
		<h3>Blend Messenger</h3>
		<address>Demo: <a href="http://www.adelineinteractive.com/Blend">www.adelineinteractive.com/Blend</a></address>
		<p>This Will be the description of the Project</p>
		<ul>
			<li>
				<img src="/images/work/default.jpg" alt="Blend Messenger" />
			</li>
			<li>
				<img src="/images/work/default.jpg" alt="Blend Messenger" />
			</li>
			<li>
				<img src="/images/work/default.jpg" alt="Blend Messenger" />
			</li>
		</ul>
	</li>
	<li class="featEncompass project">
		<h3>Encompass Institute</h3>
		<address>Demo: <a href="http://www.encompassinstitute.org">www.encompassinstitute.org</a></address>
		<p>This Will be the description of the Project</p>
		<ul>
			<li>
				<img src="/images/work/default.jpg" alt="Encompass Institute" />
			</li>
			<li>
				<img src="/images/work/default.jpg" alt="Encompass Institute" />
			</li>
			<li>
				<img src="/images/work/default.jpg" alt="Encompass Institute" />
			</li>
		</ul>
	</li>
	<li class="featJohnny project">
		<h3>Johnny Le Films</h3>
		<address>Demo: <a href="http://www.johnnylefilms.com">www.johnnylefilms.com</a></address>
		<p>This Will be the description of the Project</p>
		<ul>
			<li>
				<img src="/images/work/default.jpg" alt="Johnny Le Films" />
			</li>
			<li>
				<img src="/images/work/default.jpg" alt="Johnny Le Films" />
			</li>
			<li>
				<img src="/images/work/default.jpg" alt="Johnny Le Films" />
			</li>
		</ul>
	</li>
	<li class="featHawaiian project">
		<h3>Hawaiian Numbers</h3>
		<address>Demo: <a href="http://adelineinteractive.com/Jessica/hawaiianNumbers/">www.adelineinteractive.com/Jessica/hawaiianNumbers/</a></address>
		<p>This Will be the description of the Project</p>
		<ul>
			<li>
				<img src="/images/work/default.jpg" alt="Hawaiian Numbers" />
			</li>
				<img src="/images/work/default.jpg" alt="Hawaiian Numbers" />
			</li>
				<img src="/images/work/default.jpg" alt="Hawaiian Numbers" />
			</li>
		</ul>
	</li>
</ul>

<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>

<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>

<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>

<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>

<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>