<div class="headline">
	<h2>Welcome</h2>
	<p>JMT WebDesign+Development is the portfolio of Jessica M. Tsuji. I&rsquo;m an interactive designer &amp; developer based out of Portland, OR. My passion is infusing form &amp; function into online experiences. </p>
</div>

<ul id="featuredWork">
	<li id="blend" class="featBlend project">
		<h3 class="tab">Blend Messenger</h3>
		<address>Demo: <a href="http://www.adelineinteractive.com/Blend">Launch Blend</a></address>
		<p><strong>Overview:</strong>This Will be the description of the Project</p>
		<div class="gallery">
			<div class="overlay">
				<a class="previous" href="#">&laquo; Previous</a>
				<a class="view" href="/work/index/project/blend/#blend">View this Project</a>
				<a class="next" href="#">Next &raquo;</a>
			</div>
			<ul>
				<li>
					<img src="/images/work/blend_full.jpg" alt="Blend Messenger" />
				</li>
				<li>
					<img src="/images/work/blend_full2.jpg" alt="Blend Messenger" />
				</li>
				<li>
					<img src="/images/work/default.jpg" alt="Blend Messenger" />
				</li>
			</ul>
		</div>
	</li>
	<li id="encompass" class="featEncompass project">
		<h3 class="tab">Encompass Institute</h3>
		<address>Demo: <a href="http://www.encompassinstitute.org">Launch Encompass</a></address>
		<p><strong>Overview:</strong>This Will be the description of the Project</p>
		<div class="gallery">
			<div class="overlay">
				<a class="previous" href="#">&laquo; Previous</a>
				<a class="view" href="/work/index/project/encompass/#encompass">View this Project</a>
				<a class="next" href="#">Next &raquo;</a>
			</div>
			<ul>
				<li>
					<img src="/images/work/default.jpg" alt="Blend Messenger" />
				</li>
				<li>
					<img src="/images/work/default.jpg" alt="Blend Messenger" />
				</li>
				<li>
					<img src="/images/work/default.jpg" alt="Blend Messenger" />
				</li>
			</ul>
		</div>
	</li>
	<li id="johnny" class="featJohnny project">
		<h3 class="tab">Johnny Le Films</h3>
		<address>Demo: <a href="http://www.johnnylefilms.com">Launch Johnny Le</a></address>
		<p><strong>Overview:</strong>This Will be the description of the Project</p>
		<div class="gallery">
			<div class="overlay">
				<a class="previous" href="#">&laquo; Previous</a>
				<a class="view" href="/work/index/project/johnny/#johnny">View this Project</a>
				<a class="next" href="#">Next &raquo;</a>
			</div>
			<ul>
				<li>
					<img src="/images/work/blend_full.jpg" alt="Blend Messenger" />
				</li>
				<li>
					<img src="/images/work/default.jpg" alt="Blend Messenger" />
				</li>
				<li>
					<img src="/images/work/default.jpg" alt="Blend Messenger" />
				</li>
			</ul>
		</div>
	</li>
	<li id="hawaiian" class="featHawaiian project">
		<h3 class="tab">Hawaiian Numbers</h3>
		<address>Demo: <a href="http://adelineinteractive.com/Jessica/hawaiianNumbers/">Launch Hawaiian Numbers</a></address>
		<p><strong>Overview:</strong>This Will be the description of the Project</p>
		<div class="gallery">
			<div class="overlay">
				<a class="previous" href="#">&laquo; Previous</a>
				<a class="view" href="/work/index/project/hawaiian/#hawaiian">View this Project</a>
				<a class="next" href="#">Next &raquo;</a>
			</div>
			<ul>
				<li>
					<img src="/images/work/default.jpg" alt="Blend Messenger" />
				</li>
				<li>
					<img src="/images/work/default.jpg" alt="Blend Messenger" />
				</li>
				<li>
					<img src="/images/work/default.jpg" alt="Blend Messenger" />
				</li>
			</ul>
		</div>
	</li>
	<li class="active">
		<h3 class="arrow"></h3>
	</li>
</ul>