<div class="headline">
	<h2>My Work</h2>
	<p>I strongly believe in the ideology of doing what you love. For me that means creating quality interactive experiences that are meant to be used &amp; are built on strong ideals to be proud of. Whether that foundation is built on a strong sense of accessibility &amp; design or well structured object oriented MVC programming, it&rsquo;s the functional results that keep my passion for the Web alive &amp; burning.</p>
</div>

<ul id="featuredWork">
	<li class="featBlend project">
		<h3>Blend Messenger</h3>
		<address>Demo: <a href="http://www.adelineinteractive.com/Blend">Launch Blend</a></address>
		<p><strong>Overview:</strong>This Will be the description of the Project</p>
		<ul>
			<li>
				<img src="/images/work/default.jpg" alt="Blend Messenger" />
			</li>
			<li>
				<img src="/images/work/default.jpg" alt="Blend Messenger" />
			</li>
			<li>
				<img src="/images/work/default.jpg" alt="Blend Messenger" />
			</li>
		</ul>
	</li>
	<li class="featEncompass project">
		<h3>Encompass Institute</h3>
		<address>Demo: <a href="http://www.encompassinstitute.org">Launch Encompass</a></address>
		<p><strong>Overview:</strong>This Will be the description of the Project</p>
		<ul>
			<li>
				<img src="/images/work/default.jpg" alt="Encompass Institute" />
			</li>
			<li>
				<img src="/images/work/default.jpg" alt="Encompass Institute" />
			</li>
			<li>
				<img src="/images/work/default.jpg" alt="Encompass Institute" />
			</li>
		</ul>
	</li>
	<li class="featJohnny project">
		<h3>Johnny Le Films</h3>
		<address>Demo: <a href="http://www.johnnylefilms.com">Launch Johnny Le</a></address>
		<p><strong>Overview:</strong>This Will be the description of the Project</p>
		<ul>
			<li>
				<img src="/images/work/default.jpg" alt="Johnny Le Films" />
			</li>
			<li>
				<img src="/images/work/default.jpg" alt="Johnny Le Films" />
			</li>
			<li>
				<img src="/images/work/default.jpg" alt="Johnny Le Films" />
			</li>
		</ul>
	</li>
	<li class="featHawaiian project">
		<h3>Hawaiian Numbers</h3>
		<address>Demo: <a href="http://adelineinteractive.com/Jessica/hawaiianNumbers/">Launch Hawaiian Numbers</a></address>
		<p><strong>Overview:</strong>This Will be the description of the Project</p>
		<ul>
			<li>
				<img src="/images/work/default.jpg" alt="Hawaiian Numbers" />
			</li>
				<img src="/images/work/default.jpg" alt="Hawaiian Numbers" />
			</li>
				<img src="/images/work/default.jpg" alt="Hawaiian Numbers" />
			</li>
		</ul>
	</li>
	<li class="active">
		<h3 class="arrow"></h3>
	</li>
</ul>