<div class="headline">
	<h2>My Work</h2>
	<p>I strongly believe in the ideology of doing what you love. For me that means creating quality interactive experiences that are meant to be used &amp; founded on strong ideals to be proud of. Whether that foundation is built on a strong sense of accessibility &amp; design or well structured object oriented MVC programming, it&rsquo;s the functional results that keep my passion for the Web alive &amp; burning.</p>
</div>

<ul class="nav work individual">
	
	<li id="<?= $this->proj['selector'] ?>" class="project<?= ($this->proj['open'] == 'open') ? " individOpen" : ""; ?>">
		<a class="title" href="/work/individual/project/blend" title="Blend Messenger">
			<span><?= $this->proj['title'] ?></span>
		</a>
		<div class="full">
			<div class="meta">
				<a class="view" href="<?= $this->proj['url'] ?>" title="<?= $this->proj['title'] ?>">View This Project</a>
				<p class="role"><strong>Role: </strong><?= $this->proj['role'] ?></p>
				<p class="date"><strong>Date Completed: </strong><?= $this->proj['date'] ?></p>
			</div>
			
			<div class="gallery">
				<div class="overlay">
					<a class="previous" href="#">&laquo; Previous</a>
					<a class="next" href="#">Next &raquo;</a>
				</div>
				<ul>
					<?php 	foreach( $this->proj['photos'] as $photo ) { ?>
					<li>
						<img src="<?= $photo['url'] ?>" alt="<?= $this->proj['title'] ?>" />
					</li>
					<?		} ?>
				</ul>
			</div>
			
			<div class="info">
				<div class="overview">
					<h3>Overview:</h3>
					<?= $this->proj['overview'] ?>
				</div>
				<div class="tech">
					<h3>Tech Specs:</h3>
					<ul>
						<?php 	foreach( $this->proj['tech'] as $tech ) { ?>
						<li>
							<?= $tech ?>
						</li>
						<?		} ?>
					</ul>
				</div>
			</div>
		</div>
		
		<img class="thumb" src="/images/work/<?= $this->proj['selector'] ?>_thumb.jpg" alt="<?= $this->proj['title'] ?>" />
	</li>
</ul>