<div class="col1">
	<div class="headline">
		<h2>Contact Me</h2>
		<p>Shoot me a message if you&rsquo;re interested in learning more about my work or starting a conversation. I&rsquo;d really love to hear from you.</p>
	</div>
	<div class="contact">
		<form id="mail" method="post" action="/contact/mail">
 			<fieldset>
 				<div class="userInput">
	 				<label>Your Name:</label>
	 				<input type="text" name="name" id="name" value="Your Name" />
	 				<label>Your Email Address:</label>
	 				<input type="text" name="email" id="email" value="Your Email Address" />
	 				
	 				<span id="alert">You entered something wrong</span>
	 				
	 				<label>Your Message:</label>
	 				<textarea rows="5" name="message" id="message">Your Message</textarea>
	 			</div>
 				
 				<button type="submit" name="send" id="send">Send Your Message</button>
 			</fieldset>
 		</form>
<!--
 		<div id="mail" class="success">
 			<div class="userInput">
	 			<span id="name">Name</span>
	 			<span id="email">email</span>
	 			
	 			<p id="message">User's Message</p>
	 		</div>
 					
			<div id="thankYou">
				<p>Thank You Very Much</p>
				<span>Sent Your Message</span>
			</div>
		</div>
-->
	</div>
</div>

<div class="col2">
	<div class="widget">
		<h3>A Sneak Peek At What I'm Doing</h3>
		
		<span class="update">
			<img src="/images/me.jpg" alt="Jessica M. Tsuji" />
			<h5>September 18, 2009</h5>
			<span>I graduate today and stuff. There is a lot going on. It is very exciting. I graduate today and stuff. There is a lot going on. It is very exciting. I graduate today and stuff. There is a lot going on. It is very exciting. I graduate today and stuff. There is a lot going on. It is very exciting.I graduate today and stuff. There is a lot going on. It is very exciting. I graduate today and stuff. There is a lot going on. It is very exciting.</span>
		</span>
		
		<span class="update">
			<img src="/images/me.jpg" alt="Jessica M. Tsuji" />
			<h5>September 18, 2009</h5>
			<span>I graduate today and stuff. There is a lot going on. It is very exciting. I graduate today and stuff. There is a lot going on. It is very exciting. I graduate today and stuff. There is a lot going on. It is very exciting. I graduate today and stuff. There is a lot going on. It is very exciting.I graduate today and stuff. There is a lot going on. It is very exciting. I graduate today and stuff. There is a lot going on. It is very exciting.</span>
		</span>
		
		<span class="update">
			<img src="/images/me.jpg" alt="Jessica M. Tsuji" />
			<h5>September 18, 2009</h5>
			<span>I graduate today and stuff. There is a lot going on. It is very exciting. I graduate today and stuff. There is a lot going on. It is very exciting. I graduate today and stuff. There is a lot going on. It is very exciting. I graduate today and stuff. There is a lot going on. It is very exciting.I graduate today and stuff. There is a lot going on. It is very exciting. I graduate today and stuff. There is a lot going on. It is very exciting.</span>
		</span>
		
		<h4>More Ways to Reach Me:</h4>
		<ul class="networks">
			<li class="behance">
				<a href="#">Behance</a>
			</li>
			<li class="twitter">
				<a href="#">Twitter</a>
			</li>
			<li class="facebook">
				<a href="#">Facebook</a>
			</li>
			<li class="linkedin">
				<a href="#">LinkedIn</a>
			</li>
			<li class="delicious">
				<a href="#">Delicious</a>
			</li>
			<li class="wordpress">
				<a href="#">Wordpress</a>
			</li>
			<li class="flickr">
				<a href="#">Flickr</a>
			</li>
		</ul>
	</div>
</div>