<div class="col1">
	<div class="headline">
		<h2>Contact Me</h2>
		<p>Shoot me a message if you&rsquo;re interested in learning more about my work or starting a conversation. I&rsquo;d really love to hear from you.</p>
	</div>
	
	<div class="contact<?php if ( $this->success != "" ) echo " success"; ?>">
		<form id="mail" method="post" action="/contact/mail">
 			<fieldset>
 				<div class="userInput">
	 				<label>Your Name:</label>
	 				<input type="text" name="name" id="name" value="<?= $this->name ?>" />
	 				<label>Your Email Address:</label>
	 				<input type="text" name="email" id="email" value="<?= $this->email ?>" />
	 				
	 				<?php 	if ( $this->alert != "" ) { 
	 							foreach( $this->alert as $a ) { ?>
	 				<span class="alert">
	 					<?php 		echo $a; ?>
	 				</span>
	 				<?php		}
	 						} ?>
	 				
	 				<label>Your Message:</label>
	 				<textarea rows="5" name="message" id="message"><?= $this->message ?></textarea>
	 			</div>
 				
 				<button type="submit" name="send" id="send">Send Your Message</button>
 			</fieldset>
 		</form>

 		<div id="mail" class="success">
 			<div class="userInput">
	 			<span id="name"><?= $this->name ?></span>
	 			<span id="email"><?= $this->email ?></span>
	 			
	 			<p id="message"><?= (strlen( $this->message ) > 451 ) ? substr( stripslashes( $this->message ), 0, 450 ) . "[...]" : stripslashes($this->message) ?></p>
	 			<a id="another" href="/contact/another" title="Send Another Message">Send Another Message</a>
	 		</div>
 					
			<div id="thankYou">
				<p>Thank You Very Much</p>
				<span>Sent Your Message</span>
			</div>
		</div>

	</div>
</div>

<div class="col2">
	<div class="widget">
		<h3>A Sneak Peek At What I'm Doing</h3>
		
		<?php	foreach ( $this->updates as $update ) { ?>
		<span class="update">
			<img src="/images/updates/<?= $update['img_url'] ?>" alt="update" />
			<h5><?= $update['date'] ?></h5>
			<span><?= $update['message'] ?></span>
		</span>
		<?php	} ?>
		
		<h4>More Ways to Reach Me:</h4>
		<ul class="networks">
			<li class="behance">
				<a href="http://www.behance.net/jessica_tsuji" title="Behance Portfolio">Behance</a>
			</li>
			<li class="twitter">
				<a href="http://twitter.com/jessica_tsuji" title="Twitter Feed">Twitter</a>
			</li>
			<li class="facebook">
				<a href="http://www.facebook.com/jessicatsuji" title="Facebook Profile">Facebook</a>
			</li>
			<li class="linkedin">
				<a href="http://www.linkedin.com/in/jessicatsuji" title="LinkedIn Profile">LinkedIn</a>
			</li>
			<li class="delicious">
				<a href="http://delicious.com/jessica_tsuji" title="Delicious Links">Delicious</a>
			</li>
			<li class="wordpress">
				<a href="http://www.adelineinteractive.com/logicbored/" title="LogicBored Blog">Wordpress Blog</a>
			</li>
			<li class="flickr">
				<a href="http://www.flickr.com/photos/jessica_tsuji">Flickr</a>
			</li>
		</ul>
	</div>
</div>