<div class="col1">
	<div class="headline">
		<h2>Contact Me</h2>
		<p>Shoot me a message if you&rsquo;re interested in learning more about my work or starting a conversation. I&rsquo;d really love to hear from you.</p>
	</div>
	<div class="contact">
		<form>
		</form>
	</div>
</div>

<div class="col2">
	<div class="widget">
		<h3>A Few of My Favorite Things</h3>
		<ul class="interests1">
			<li>
				<a href="#">Web Standards</a>
			</li>
			<li>
				<a href="#">UX / UI Design</a>
			</li>
			<li>
				<a href="#">Web App Development</a>
			</li>
			<li>
				<a href="#">Semantic Markup</a>
			</li>
			<li>
				<a href="#">Social Media</a>
			</li>
			<li>
				<a href="#">Analytics / SEO</a>
			</li>
		</ul>
		<ul class="interests2">
			<li>
				<a href="#">MVC Pattern</a>
			</li>
			<li>
				<a href="#">OOP</a>
			</li>
			<li>
				<a href="#">Multidisciplinary Media</a>
			</li>
			<li>
				<a href="#">User Centered Design</a>
			</li>
			<li>
				<a href="#">Form AND Function</a>
			</li>
			<li>
				<a href="#">Quality over Quantity</a>
			</li>
		</ul>
		
		<h4>Clients:</h4>
		<ul class="clients">
			<li>
				<a href="#">Encompass Institute</a>
			</li>
			<li>
				<a href="#">Art Institute of Portland Web Raising</a>
			</li>
			<li>
				<a href="#">Neighborhood Natural Energy (N2e)</a>
			</li>
			<li>
				<a href="#">Oregon Zoo Kids Zone</a>
			</li>
			<li>
				<a href="#">Johnny Le Films</a>
			</li>
			<li>
				<a href="#">Kurt Nishimura</a>
			</li>
			<li>
				<a href="#">Hollywood Boosters</a>
			</li>
			<li>
				<a href="#">Virginia Garcia Memorial Health Center</a>
			</li>
		</ul>
		
		<h4>Inspiration:</h4>
		<ul class="friends1">
			<li>
				<a href="#">Kellan Craddock</a>
			</li>
			<li>
				<a href="#">Substance, Inc.</a>
			</li>
			<li>
				<a href="#">Gerardo Rodriguez</a>
			</li>
			<li>
				<a href="#">Damir Tuka</a>
			</li>
		</ul>
		<ul class="friends2">
			<li>
				<a href="#">Johnny Le</a>
			</li>
			<li>
				<a href="#">Jerylyn Brei</a>
			</li>
			<li>
				<a href="#">Kurt Nishimura</a>
			</li>
			<li>
				<a href="#">Colorcubic</a>
			</li>
		</ul>
	</div>
</div>