<div class="col1">
	<div class="headline">
		<h2>About Me</h2>
		<p>My name is Jessica M. Tsuji and I am an Interactive Designer & Developer who strongly believes in doing what you love.</p>
	</div>
	<div class="about">
		<img src="/images/me.jpg" alt="Jessica M. Tsuji" />
		<p>Upon leaving my island home of Maui, Hawaii to pursue a higher education in Portland, Oregon, I uncovered an overwhelming passion for the Web. For me, it&rsquo;s not simply a communication tool; it&rsquo;s an immersive experience ingrained directly into life.</p>
		<p>Concepts like accessibility and user experience aren&rsquo;t just buzzwords for me; They&rsquo;re a part of life. Through implementing better design practices, web standards, and clean extensible code, I believe the online world can be a better place.</p>
		<p>I strongly believe form &amp; function hold equal importance, especially on the Web. My love for design only serves to fuel my passion for carrying out functionality through XHTML, CSS, JavaScript, &amp; PHP.</p>
	</div>
	<div class="resume">
		<a href="/downloads/resume.pdf">Download My Resume</a>
	</div>
</div>

<div class="col2">
	<div class="widget">
		<h3>A Few of My Favorite Things</h3>
		<ul class="interests1">
			<li>
				<a href="http://www.w3.org/" title="World Wide Consortium">Web Standards</a>
			</li>
			<li>
				<a href="http://ui-patterns.com/" title="UI Patterns">UX / UI Design</a>
			</li>
			<li>
				<a href="http://en.wikipedia.org/wiki/Web_application_development" title="Web Application Development Wiki">Web App Development</a>
			</li>
			<li>
				<a href="http://en.wikipedia.org/wiki/Semantic_Web" title="Sematic Web Wiki">Semantic Web</a>
			</li>
			<li>
				<a href="http://en.wikipedia.org/wiki/Social_media" title="Social Media">Social Media</a>
			</li>
			<li>
				<a href="http://www.google.com/analytics/" title="Google Analytics">Analytics / SEO</a>
			</li>
		</ul>
		<ul class="interests2">
			<li>
				<a href="http://en.wikipedia.org/wiki/Model-View-Controller" title="MVC Wiki">MVC Pattern</a>
			</li>
			<li>
				<a href="http://en.wikipedia.org/wiki/Object-oriented_programming" title="Object Oriented Programming">OOP</a>
			</li>
			<li>
				<a href="http://www.amazon.com/Design-Real-World-Ecology-Social/dp/0897331532" title="Design for the Real World by Victor Papanek">Multidisciplinary Media</a>
			</li>
			<li>
				<a href="http://en.wikipedia.org/wiki/User-centered_design" title="User Centered Design">User Centered Design</a>
			</li>
			<li>
				<a href="http://www.digital-web.com/articles/form_vs_function/" title="Form and Function Balance">Form AND Function</a>
			</li>
			<li>
				<a href="http://findsubstance.com/2009/07/16/more-social-less-media/" title="More Social, Less Media">Quality over Quantity</a>
			</li>
		</ul>
		
		<h4>Clients:</h4>
		<ul class="clients">
			<li>
				<a href="http://www.encompassinstitute.org/" title="Encompass Institute">Encompass Institute</a>
			</li>
			<li>
				<a href="http://www.aipdwebraising.com/" title="WebRaising Event at the Art Institute of Portland">Art Institute of Portland Web Raising</a>
			</li>
			<li>
				<a href="http://www.n2e.org/" title="n2e">Neighborhood Natural Energy (N2e)</a>
			</li>
			<li>
				<a href="http://www.oregonzoo.org/KidsZone/" title="Oregon Zoo KidsZone">Oregon Zoo Kids Zone</a>
			</li>
			<li>
				<a href="http://www.johnnylefilms.com/" title="Johnny Le Films">Johnny Le Films</a>
			</li>
			<li>
				<a href="http://www.kurtnishimura.com/" title="Kurt Nishimura">Kurt Nishimura</a>
			</li>
			<li>
				<a href="http://www.hollywoodboosters.com/" title="Hollywood Boosters">Hollywood Boosters</a>
			</li>
			<li>
				<a href="http://www.virginiagarcia.org/" title="Virginia Garcia Memorial Health Center">Virginia Garcia Memorial Health Center</a>
			</li>
		</ul>
		
		<h4>Inspiration:</h4>
		<ul class="friends1">
			<li>
				<a href="http://www.kellancraddock.com/" title="Kellan Craddock">Kellan Craddock</a>
			</li>
			<li>
				<a href="http://www.findsubstance.com/" title="Substance, Inc.">Substance, Inc.</a>
			</li>
			<li>
				<a href="http://www.gerardo-rodriguez.com/" title="Gerardo Rodriguez">Gerardo Rodriguez</a>
			</li>
			<li>
				<a href="http://www.devisemethod.com/" title="Damir Tuka">Damir Tuka</a>
			</li>
		</ul>
		<ul class="friends2">
			<li>
				<a href="http://www.johnnylefilms.com" title="Johnny Le">Johnny Le</a>
			</li>
			<li>
				<a href="http://jerylyn.tumblr.com/" title="Jerylyn Brei">Jerylyn Brei</a>
			</li>
			<li>
				<a href="http://www.kurtnishimura.com/" title="Kurt Nishimura">Kurt Nishimura</a>
			</li>
			<li>
				<a href="http://www.colorcubic.com" title="Colorcubic">Colorcubic</a>
			</li>
		</ul>
	</div>
</div>