<div class="col1">
	<div class="headline">
		<h2>About Me</h2>
		<p>My name is Jessica M. Tsuji and I am an Interactive Designer & Developer who strongly believes in doing what you love.</p>
	</div>
	<div class="about">
		<img src="/images/me.jpg" alt="Jessica M. Tsuji" />
		<p>Upon leaving my island home of Maui, Hawaii to pursue a higher education in Portland, Oregon, I uncovered an overwhelming passion for the Web. For me, it&rsquo;s not simply a communication tool; it&rsquo;s an immersive experience ingrained directly into life.</p>
		<p>Concepts like accessibility and user experience aren&rsquo;t just buzzwords for me; They&rsquo;re a part of life. Through implementing better design practices, web standards, and clean extensible code, I believe the online world can be a better place.</p>
		<p>I strongly believe form &amp; function hold equal importance, especially on the Web. My love for design only serves to fuel my passion for carrying out functionality through XHTML, CSS, JavaScript, &amp; PHP.</p>
	</div>
	<div class="resume">
		<a href="#">Download My Resume</a>
	</div>
</div>

<div class="col2">
	<div class="widget">
		<h3>A Few of My Favorite Things</h3>
		<ul class="interests1">
			<li>
				<a href="#">Web Standards</a>
			</li>
			<li>
				<a href="#">UX / UI Design</a>
			</li>
			<li>
				<a href="#">Web App Development</a>
			</li>
			<li>
				<a href="#">Semantic Markup</a>
			</li>
			<li>
				<a href="#">Social Media</a>
			</li>
			<li>
				<a href="#">Analytics / SEO</a>
			</li>
		</ul>
		<ul class="interests2">
			<li>
				<a href="#">MVC Pattern</a>
			</li>
			<li>
				<a href="#">OOP</a>
			</li>
			<li>
				<a href="#">Multidisciplinary Media</a>
			</li>
			<li>
				<a href="#">User Centered Design</a>
			</li>
			<li>
				<a href="#">Form AND Function</a>
			</li>
			<li>
				<a href="#">Quality over Quantity</a>
			</li>
		</ul>
		
		<h4>Clients:</h4>
		<ul class="clients">
			<li>
				<a href="#">Encompass Institute</a>
			</li>
			<li>
				<a href="#">Art Institute of Portland Web Raising</a>
			</li>
			<li>
				<a href="#">Neighborhood Natural Energy (N2e)</a>
			</li>
			<li>
				<a href="#">Oregon Zoo Kids Zone</a>
			</li>
			<li>
				<a href="#">Johnny Le Films</a>
			</li>
			<li>
				<a href="#">Kurt Nishimura</a>
			</li>
			<li>
				<a href="#">Hollywood Boosters</a>
			</li>
			<li>
				<a href="#">Virginia Garcia Memorial Health Center</a>
			</li>
		</ul>
		
		<h4>Inspiration:</h4>
		<ul class="friends1">
			<li>
				<a href="#">Kellan Craddock</a>
			</li>
			<li>
				<a href="#">Substance, Inc.</a>
			</li>
			<li>
				<a href="#">Gerardo Rodriguez</a>
			</li>
			<li>
				<a href="#">Damir Tuka</a>
			</li>
		</ul>
		<ul class="friends2">
			<li>
				<a href="#">Johnny Le</a>
			</li>
			<li>
				<a href="#">Jerylyn Brei</a>
			</li>
			<li>
				<a href="#">Kurt Nishimura</a>
			</li>
			<li>
				<a href="#">Colorcubic</a>
			</li>
		</ul>
	</div>
</div>