<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
	<title>JMT Web Design+Development - The Portfolio of Jessica M. Tsuji</title>
	
	<link type="text/css" href="/css/master.css" rel="stylesheet" />
	<link type="text/css" href="/css/sIFR-print.css" rel="stylesheet" media="print" />
	<link type="text/css" href="/css/sIFR-screen.css" rel="stylesheet" media="screen" />
	<script type="text/javascript" src="/js/jquery.js" language="javascript"></script>
	<script type="text/javascript" src="/js/easing.js" language="javascript"></script>
	<script type="text/javascript" src="/js/jquery.tweet.js" language="javascript"></script>  
	<script type="text/javascript" src="/js/sifr.js" language="javascript"></script>
	<script type="text/javascript">
		$(function() {
			//sIFR
			sIFR.replaceElement(".headline>p", named({sFlashSrc: "/swf/quicksand.swf", sColor: "#770015", sBgColor: "#d6d6d6", sWmode: "transparent"}));
			
			//Javascript FeatureBox
			$('#featuredWork').addClass('enabled');
			$('.featBlend').prepend('<h3 class="activeTxt"><!-- --></h3>');	
			$('.activeTxt').show();	
			
			$('#featuredWork h3').click(function() {
				$('.activeTxt').animate({opacity:1}, 500).fadeOut(800, function() {
					$(this).remove();	
				});
				
				$(this).parent().prepend('<h3 class="activeTxt"><!-- --></h3>');
				
				$('.activeTxt').animate({opacity:1}, 500).fadeIn(1000);
				
				var topPos = $(this).css('top');
				$('.arrow').animate({
					top: topPos
				}, {"duration": 1200, "easing": "easeInOutElastic"});
			});
			
			$('#featuredWork h3.arrow').unbind('click');
			
			//Twitter
			$(".tweet").tweet({
	            username: "jessica_tsuji",
	            join_text: "auto",
	            avatar_size: 50,
	            count: 1,
	            auto_join_text_default: "",
	            auto_join_text_ed: "",
	            auto_join_text_ing: "",
	            auto_join_text_reply: "",
	            auto_join_text_url: "",
	            loading_text: "loading tweets..."
	        });
	        
	        //Social Nav
	        $('#social').append('<span class="socialType"></span>');
	        $('#social .nav li a').hover(function() {
	        	$('#social .socialType').text($(this).attr('title'));
	        }, function() {
	        	$('#social .socialType').text("");
	        });
		});
	</script>


</head>

<body id="<?= $this->page; ?>">

	<div id="headerWrapper">
		<div id="headerContent">
			<h1><a href="/" id="logo" title="Jessica Tsuji's Portfolio Logo">JMT Web Design+Development</a></h1>
			<div id="contactInfo">
				<span class="email">jessica.tsuji@gmail.com</span>
				<span class="phone">808.344.4729</span>
			</div>
			<ul class="nav">
				<li class="navWork">
					<a href="/work">What I Love</a>
				</li>
				<li class="navAbout">
					<a href="/about">Who I Am</a>
				</li>
				<li class="navContact">
					<a href="/contact">Say Hi</a>
				</li>
			</ul>
		</div>
	</div>
	
	<div id="bodyWrapper">
		<div id="mainWrapper">
			<div id="mainContent">
				<?= $this->layout()->content ?>
			</div>
		</div>
	</div>
	
	<div id="footerWrapper">
		<div id="footerContent">
			<div class="footMeta">
				<ul class="foot nav">
					<li class="navHome">
						<a href="/">Home</a>
					</li>
					<li class="navWork">
						<a href="/work">Work</a>
					</li>
					<li class="navAbout">
						<a href="/about">About</a>
					</li>
					<li class="navContact">
						<a href="/contact">Contact</a>
					</li>
				</ul>
				<span class="copyright">&copy;2009, Jessica M. Tsuji. ALL RIGHTS RESERVED.</span>
			</div>
			<div id="twitter">
				<h5>What Am I Saying?</h5>
				<div class="tweet"></div>
			</div>
			<div id="social">
				<ul class="nav">
					<li class="navBehance">
						<a href="http://www.behance.net/jessica_tsuji" title="Behance Portfolio">Behance</a>
					</li>
					<li class="navTwitter">
						<a href="http://twitter.com/jessica_tsuji" title="Twitter Feed">Twitter</a>
					</li>
					<li class="navLinkedIn">
						<a href="http://www.linkedin.com/in/jessicatsuji" title="LinkedIn Profile">LinkedIn</a>
					</li>
					<li class="navFacebook">
						<a href="http://www.facebook.com/jessicatsuji" title="Facebook Profile">Facebook</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
		
</body>
</html>