<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
	<title>JMT Web Design+Development - The Portfolio of Jessica M. Tsuji</title>
	
	<link type="text/css" href="/css/master.css" rel="stylesheet" />
	<link type="text/css" href="/css/sIFR-print.css" rel="stylesheet" media="print" />
	<link type="text/css" href="/css/sIFR-screen.css" rel="stylesheet" media="screen" />
	
	<script type="text/javascript" src="/js/libraries/jquery.js"></script>
	
	<script type="text/javascript" src="/js/plugins/easing.js"></script>
	<script type="text/javascript" src="/js/plugins/jquery.tweet.js"></script>  
	<script type="text/javascript" src="/js/plugins/sifr.js"></script>
	<script type="text/javascript" src="/js/plugins/animateBgPosition.js"></script>
	<script type="text/javascript" src="/js/plugins/pngFix.pack.js"></script>
	
	<script type="text/javascript" src="/js/views/BaseView.js"></script>
	<script type="text/javascript" src="/js/views/View.js"></script>
	<script type="text/javascript" src="/js/controllers/BaseController.js"></script>
	<script type="text/javascript" src="/js/models/BaseModel.js"></script>
	<script type="text/javascript" src="/js/models/IndexModel.js"></script>
	<script type="text/javascript" src="/js/controllers/<?= ucwords($this->page); ?>Controller.js"></script>
	<script type="text/javascript" src="/js/helpers/GalleryHelper.js"></script>
	
	
	<script type="text/javascript">
	
	</script>


</head>

<body id="<?= $this->page; ?>">

	<div id="headerWrapper">
		<div id="headerContent">
			<h1><a href="/" id="logo" title="Jessica Tsuji's Portfolio Logo">JMT Web Design+Development</a></h1>
			<div id="contactInfo">
				<span class="email">jessica.tsuji@gmail.com</span>
				<span class="phone">808.344.4729</span>
			</div>
			<ul class="nav">
				<li class="navWork">
					<a href="/work">What I Love</a>
				</li>
				<li class="navAbout">
					<a href="/about">Who I Am</a>
				</li>
				<li class="navContact">
					<a href="/contact">Say Hi</a>
				</li>
			</ul>
		</div>
	</div>
	
	<div id="bodyWrapper">
		<div id="mainWrapper">
			<div id="mainContent">
				<?= $this->layout()->content ?>
			</div>
		</div>
	</div>
	
	<div id="footerWrapper">
		<div id="footerContent">
			<div class="footMeta">
				<ul class="foot nav">
					<li class="navHome">
						<a href="/">Home</a>
					</li>
					<li class="navWork">
						<a href="/work">Work</a>
					</li>
					<li class="navAbout">
						<a href="/about">About</a>
					</li>
					<li class="navContact">
						<a href="/contact">Contact</a>
					</li>
				</ul>
				<span class="copyright">&copy;2009, Jessica M. Tsuji. ALL RIGHTS RESERVED.</span>
			</div>
			<div id="twitter">
				<h5>What Am I Saying?</h5>
				<div class="tweet"></div>
			</div>
			<div id="social">
				<ul class="nav">
					<li class="navBehance">
						<a href="http://www.behance.net/jessica_tsuji" title="Behance Portfolio">Behance</a>
					</li>
					<li class="navTwitter">
						<a href="http://twitter.com/jessica_tsuji" title="Twitter Feed">Twitter</a>
					</li>
					<li class="navLinkedIn">
						<a href="http://www.linkedin.com/in/jessicatsuji" title="LinkedIn Profile">LinkedIn</a>
					</li>
					<li class="navFacebook">
						<a href="http://www.facebook.com/jessicatsuji" title="Facebook Profile">Facebook</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
		
</body>
</html>